### ISSUE TITLE
Add !why

### ISSUE THREAD

**Issue by microamp** [microamp/gerri#5]
e.g.

```
<microamp> !why am i here?
<gerri> blah blah
```

**Comment by kesara** [comment]
On jenni, "why" make use of http://www.leonatkinson.com/random/index.php/advice.html (https://github.com/myano/jenni/blob/master/modules/why.py#L15)
It is not really an explanation of "why" but rather an advice.
I've added advice plugin (92b099c08d908f9b6c5c1da5961b2c4c4a2bcddd)

**Comment by microamp** [comment]
Nice. Good job on formatting (gofmt?) too! :+1:

**Comment by microamp** [comment]
Does this actually work? Tried it a few times earlier, but I was getting some errors. Possibly from their server.

**Comment by kesara** [comment]
Most probably. I haven't noticed any errors in !advice.
Do you have any logs?

**Comment by microamp** [comment]
Was getting

```console
2015/02/11 20:00:58 error: Get : unsupported protocol scheme ""
```

before, but seems like it's working fine now with the latest version. 

:+1:
